In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

In [ ]:
fileCheck = pd.read_parquet("/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets/MSFT.parquet")
pd.options.display.max_columns = None
display(fileCheck)

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,ticker,spy_m5_rel_vol,spy_m5_rel_cum_vol,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_d1_atr_14,d1_trend_atr_14,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,ticker_d1,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,dist_spy_m5_yest_high,dist_spy_m5_yest_low,dist_spy_m5_yest_close,dist_spy_m5_hod,dist_spy_m5_lod,dist_spy_m5_session_open,dist_spy_m5_ema_8,dist_spy_m5_vwap,dist_spy_d1_sma_20,dist_spy_d1_sma_50,dist_spy_d1_sma_200,dist_spy_d1_ema_8,dist_spy_d1_ema_21,dist_spy_d1_high_52w,dist_spy_d1_low_52w,dist_spy_d1_prev_day_high,dist_spy_d1_prev_day_low,d1_natr,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
0,2000-01-04 09:30:00,NaN,NaN,0.420658,0.332163,0.0,1.000000,1.000000,-0.026005,-0.000275,-1,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.608761,-0.793353,0.000000e+00,1.0,0.010792,0.014134,0.000184,0.044867,-0.013487,0.026699,0.000826,-0.000275,0.000275,0.019093,0.019093,-0.000275,0.000207,NaN,NaN,NaN,NaN,0.026699,0.026699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.030278,0.044867,-0.013487,0.022984,0.033857,0.044867,-0.013487,0.026699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008497,1.0,0.022590,1.0,0.020974,1.0,0.023128,1.0,0.016110,1.0,-0.007458,1.0,-0.023674,1.0,-0.006905,1.0,0.016652,1.0
1,2000-01-04 09:35:00,1.612055,-0.045252,0.470466,-2.632883,0.0,1.000000,1.000000,-0.017694,0.008256,-1,MSFT,1.000000,1.000000,NaN,-0.019182,0.985542,14.222584,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.591310,-0.806445,0.000000e+00,1.0,0.001120,0.004319,-0.002729,0.036026,-0.021834,0.018012,0.002183,-0.008734,-0.008189,0.001107,0.002183,-0.008734,-0.003685,NaN,NaN,NaN,NaN,0.018012,0.018012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021561,0.036026,-0.021834,0.014328,0.025109,0.036026,-0.021834,0.018012,NaN,NaN,NaN,0.020394,-0.009719,0.020394,-0.000775,0.0,NaN,NaN,NaN,0.000820,0.000820,NaN,NaN,NaN,NaN,NaN,0.005987,1.0,0.013015,1.0,0.011397,1.0,0.014631,1.0,0.005444,1.0,-0.029356,1.0,-0.034995,1.0,-0.022076,1.0,0.007613,1.0
2,2000-01-04 09:40:00,2.389544,0.771308,0.619978,-1.738285,0.0,1.000000,1.000000,-0.011795,0.014311,1,MSFT,1.000000,1.000000,-0.011820,0.001089,0.479557,1.785008,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.573576,-0.819152,0.000000e+00,1.0,-0.002428,-0.001304,-0.006876,0.029842,-0.027673,0.011935,0.001627,-0.014651,-0.014109,-0.007251,0.001627,-0.014651,-0.004748,NaN,NaN,NaN,NaN,0.011935,0.011935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.015463,0.029842,-0.027673,0.008273,0.018990,0.029842,-0.027673,0.011935,0.032202,0.001741,0.012402,0.000435,-0.000870,-0.000653,0.008488,0.0,NaN,NaN,NaN,0.012402,0.012402,NaN,NaN,NaN,NaN,NaN,0.006490,1.0,0.004601,1.0,0.007566,1.0,0.010256,1.0,0.000000,1.0,-0.028063,1.0,-0.046649,1.0,-0.024164,1.0,-0.000544,1.0
3,2000-01-04 09:45:00,3.866009,0.398053,0.650672,1.404380,0.0,1.000000,1.000000,-0.005360,0.020915,1,MSFT,1.000000,1.000000,-0.013969,-0.001089,0.435599,-8.429669,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.555570,-0.831470,0.000000e+00,1.0,-0.004441,-0.006039,-0.010542,0.023180,-0.033963,0.005389,0.002695,-0.021025,-0.020487,-0.012430,0.002695,-0.013478,-0.004179,NaN,NaN,NaN,NaN,0.005389,0.005389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008894,0.023180,-0.033963,0.001751,0.012398,0.023180,-0.033963,0.005389,0.032577,0.002104,0.012770,0.001451,-0.002466,-0.000290,0.006580,0.0,NaN,NaN,NaN,0.012770,0.012770,NaN,NaN,NaN,NaN,NaN,0.002154,1.0,-0.003782,1.0,0.002154,1.0,0.003766,1.0,-0.007578,1.0,-0.037907,1.0,-0.065151,1.0,-0.033996,1.0,-0.002700,1.0
4,2000-01-04 09:50:00,2.907437,1.274839,0.640596,4.255772,0.0,1.000000,1.000000,-0.003215,0.023117,1,MSFT,1.000000,1.000000,-0.012680,0.000218,0.445078,-14.098132,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.537300,-0.843391,0.000000e+00,1.0,-0.003291,-0.006360,-0.009366,0.020978,-0.036042,0.003226,0.003226,-0.023132,-0.022594,-0.010438,0.003226,-0.010438,-0.000539,NaN,NaN,NaN,NaN,0.003226,0.003226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006723,0.020978,-0.036042,-0.000405,0.010220,0.020978,-0.036042,0.003226,0.032655,0.002180,0.012846,0.001527,-0.002391,-0.000214,0.005178,0.0,NaN,NaN,NaN,0.012846,0.012846,NaN,NaN,NaN,NaN,NaN,0.004829,1.0,-0.004313,1.0,-0.001616,1.0,0.001612,1.0,-0.012994,1.0,-0.045114,1.0,-0.060424,1.0,-0.033922,1.0,-0.008644,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506401,2025-07-25 15:40:00,-3.187223,-2.437605,0.304440,17.774860,1.0,0.872843,1.081357,0.009809,0.007838,-1,MSFT,0.607204,0.722762,0.004698,0.003559,0.917999,21.574320,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.819152,-0.573576,1.224647e-16,-1.0,0.000503,0.000986,-0.003298,-0.005065,-0.017403,-0.009714,0.003883,-0.011478,-0.007777,0.000960,0.001017,-0.000107,0.000461,-0.027423,-0.068830,-0.155170,-0.167856,-0.017360,-0.031626,-0.003186,-0.332171,-0.018391,-0.030187,-0.018410,-0.042951,-0.104138,-0.177005,-0.018347,-0.005065,-0.018347,-0.011684,-0.014556,-0.005065,-0.017403,-0.009714,-0.000311,-0.003706,-0.003156,0.001936,-0.002370,-0.002024,0.001600,0.0,-0.020021,-0.047411,-0.078022,-0.011099,-0.022766,-0.000311,-0.242867,-0.001490,-0.010400,0.011949,-0.000765,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506402,2025-07-25 15:45:00,-3.353187,-2.091420,0.144395,11.882884,0.0,0.894688,1.078775,0.009036,0.007067,-1,MSFT,0.908817,0.726364,0.004911,0.003771,1.000000,21.460234,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.831470,-0.555570,1.224647e-16,-1.0,0.000634,0.001363,-0.002503,-0.004303,-0.016651,-0.008955,0.004652,-0.010721,-0.007017,0.001477,0.001477,-0.000136,0.000359,-0.026678,-0.068117,-0.154524,-0.167218,-0.016607,-0.030885,-0.002423,-0.331660,-0.017639,-0.029444,-0.017659,-0.042218,-0.103452,-0.176375,-0.017595,-0.004303,-0.017595,-0.010928,-0.013801,-0.004303,-0.016651,-0.008955,-0.000352,-0.003747,-0.003197,0.001895,-0.002411,-0.002065,0.001590,0.0,-0.020061,-0.047450,-0.078059,-0.011139,-0.022806,-0.000352,-0.242898,-0.001531,-0.010441,0.011958,-0.001261,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506403,2025-07-25 15:50:00,-4.645053,-4.004664,0.054670,4.081138,0.0,1.406802,1.085621,0.007765,0.005798,-1,MSFT,0.846949,0.728845,0.004682,0.003543,0.902754,19.143709,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.843391,-0.537300,1.224647e-16,-1.0,0.000948,0.002043,-0.001207,-0.003047,-0.015410,-0.007705,0.005920,-0.009473,-0.005764,0.002180,0.002180,-0.001126,0.000442,-0.025450,-0.066941,-0.153457,-0.166168,-0.015367,-0.029662,-0.001164,-0.330817,-0.016400,-0.028220,-0.016420,-0.041010,-0.102321,-0.175336,-0.016356,-0.003047,-0.016356,-0.009680,-0.012557,-0.003047,-0.015410,-0.007705,-0.000388,-0.003782,-0.003232,0.001859,-0.002447,-0.002101,0.001527,0.0,-0.020096,-0.047484,-0.078093,-0.011174,-0.022841,-0.000388,-0.242925,-0.001567,-0.010476,0.011973,-0.002954,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506404,2025-07-25 15:55:00,-5.233312,-4.252124,0.105488,-8.141213,0.0,1.629662,1.108175,0.004792,0.002831,-1,MSFT,0.684967,0.727525,0.004493,0.003354,0.586184,15.525219,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.854912,-0.518773,1.224647e-16,-1.0,0.001955,0.003895,0.001689,-0.000097,-0.012497,-0.004769,0.008896,-0.006542,-0.002823,0.004274,0.004274,-0.000603,0.001324,-0.022567,-0.064180,-0.150952,-0.163701,-0.012453,-0.026791,0.001791,-0.328837,-0.013490,-0.025345,-0.013509,-0.038173,-0.099665,-0.172896,-0.013446,-0.000097,-0.013446,-0.006750,-0.009636,-0.000097,-0.012497,-0.004769,-0.000425,-0.003819,-0.003269,0.001821,-0.002484,-0.002138,0.001427,0.0,-0.020133,-0.047520,-0.078127,-0.011211,-0.022878,-0.000425,-0.242954,-0.001604,-0.010513,0.012008,0.000409,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506405,2025-07-25 16:00:00,-5.532922,-3.194700,0.138795,-15.798197,0.0,0.753124,0.977655,0.005203,0.003240,-1,MSFT,1.162845,0.746520,0.003862,0.002724,0.379329,7.227488,0.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.866025,-0.500000,1.224647e-16,-1.0,0.000773,0.002710,0.000867,-0.000506,-0.012901,-0.005176,0.008484,-0.006948,-0.003230,0.002389,0.002389,-0.001566,-0.000246,-0.022966,-0.064563,-0.151299,-0.164042,-0.012857,-0.027189,0.001382,-0.329111,-0.013893,-0.025743,-0.013912,-0.038566,-0.100033,-0.173234,-0.013849,-0.000506,-0.013849,-0.007156,-0.010040,-0.000506,-0.012901,-0.005176,-0.000474,-0.003867,-0.003317,0.001773,-0.002532,-0.002186,0.001191,0.0,-0.020180,-0.047566,-0.078171,-0.011259,-0.022925,-0.000474,-0.242990,-0.001652,-0.010561,0.012003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
fileCheck = pd.read_parquet("/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets/MSFT.parquet")
pd.options.display.max_columns = None
display(fileCheck)

,timestamp,m5_rrs_rrs_spy,m5_rrs_rrs_sector,m5_mom_lrsi,m5_mom_tsi,m5_mom_squeeze_on,m5_vol_rel_vol,m5_vol_rel_cum_vol,m5_levels_chg_from_yest_close_pct,m5_levels_chg_from_open_pct,m5_ha_ha_color,ticker,spy_m5_rel_vol,spy_m5_rel_cum_vol,spy_m5_chg_from_yest_close_pct,spy_m5_chg_from_open_pct,spy_m5_lrsi,spy_m5_tsi,spy_m5_squeeze_on,spy_d1_atr_14,d1_trend_atr_14,d1_rrs_rrs_spy_5,d1_rrs_rrs_spy_5_sma,d1_rrs_rrs_sec_5,d1_rrs_rrs_sec_5_sma,d1_rrs_rrs_spy_12,d1_rrs_rrs_spy_12_sma,d1_rrs_rrs_sec_12,d1_rrs_rrs_sec_12_sma,d1_rrs_rrs_spy_25,d1_rrs_rrs_spy_25_sma,d1_rrs_rrs_sec_25,d1_rrs_rrs_sec_25_sma,d1_ha_ha_color,d1_lrsi_laguerre_rsi_0.7,d1_adx_adx,d1_adx_plus_di,d1_adx_minus_di,ticker_d1,time_weekday,time_sin,time_cos,month_sin,month_cos,dist_m5_ma_ema_3,dist_m5_ma_ema_8,dist_m5_ma_vwap,dist_m5_levels_yest_high,dist_m5_levels_yest_low,dist_m5_levels_yest_close,dist_m5_levels_hod,dist_m5_levels_lod,dist_m5_levels_session_open,dist_m5_ha_ha_open,dist_m5_ha_ha_high,dist_m5_ha_ha_low,dist_m5_ha_ha_close,dist_d1_trend_sma_20,dist_d1_trend_sma_50,dist_d1_trend_sma_100,dist_d1_trend_sma_200,dist_d1_trend_ema_8,dist_d1_trend_ema_21,dist_d1_trend_high_52w,dist_d1_trend_low_52w,dist_d1_trend_prev_day_high,dist_d1_trend_prev_day_low,dist_d1_trend_prev_week_high,dist_d1_trend_prev_week_low,dist_d1_trend_prev_month_high,dist_d1_trend_prev_month_low,dist_d1_ha_ha_open,dist_d1_ha_ha_high,dist_d1_ha_ha_low,dist_d1_ha_ha_close,dist_open_d1,dist_high_d1,dist_low_d1,dist_close_d1,dist_spy_m5_yest_high,dist_spy_m5_yest_low,dist_spy_m5_yest_close,dist_spy_m5_hod,dist_spy_m5_lod,dist_spy_m5_session_open,dist_spy_m5_ema_8,dist_spy_m5_vwap,dist_spy_d1_sma_20,dist_spy_d1_sma_50,dist_spy_d1_sma_200,dist_spy_d1_ema_8,dist_spy_d1_ema_21,dist_spy_d1_high_52w,dist_spy_d1_low_52w,dist_spy_d1_prev_day_high,dist_spy_d1_prev_day_low,d1_natr,target_reg_5m_logret,target_cls_5m,target_reg_30m_logret,target_cls_30m,target_reg_1h_logret,target_cls_1h,target_reg_2h_logret,target_cls_2h,target_reg_4h_logret,target_cls_4h,target_reg_1d_logret,target_cls_1d,target_reg_3d_logret,target_cls_3d,target_reg_5d_logret,target_cls_5d,target_reg_10d_logret,target_cls_10d
0,2000-01-04 09:30:00,NaN,NaN,0.420658,0.332163,0.0,1.000000,1.000000,-0.026005,-0.000275,-1,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.608761,-0.793353,0.000000e+00,1.0,0.010792,0.014134,0.000184,0.044867,-0.013487,0.026699,0.000826,-0.000275,0.000275,0.019093,0.019093,-0.000275,0.000207,NaN,NaN,NaN,NaN,0.026699,0.026699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.030278,0.044867,-0.013487,0.022984,0.033857,0.044867,-0.013487,0.026699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008497,1.0,0.022590,1.0,0.020974,1.0,0.023128,1.0,0.016110,1.0,-0.007458,1.0,-0.023674,1.0,-0.006905,1.0,0.016652,1.0
1,2000-01-04 09:35:00,1.612055,-0.045252,0.470466,-2.632883,0.0,1.000000,1.000000,-0.017694,0.008256,-1,MSFT,1.000000,1.000000,NaN,-0.019182,0.985542,14.222584,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.591310,-0.806445,0.000000e+00,1.0,0.001120,0.004319,-0.002729,0.036026,-0.021834,0.018012,0.002183,-0.008734,-0.008189,0.001107,0.002183,-0.008734,-0.003685,NaN,NaN,NaN,NaN,0.018012,0.018012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021561,0.036026,-0.021834,0.014328,0.025109,0.036026,-0.021834,0.018012,NaN,NaN,NaN,0.020394,-0.009719,0.020394,-0.000775,0.0,NaN,NaN,NaN,0.000820,0.000820,NaN,NaN,NaN,NaN,NaN,0.005987,1.0,0.013015,1.0,0.011397,1.0,0.014631,1.0,0.005444,1.0,-0.029356,1.0,-0.034995,1.0,-0.022076,1.0,0.007613,1.0
2,2000-01-04 09:40:00,2.389544,0.771308,0.619978,-1.738285,0.0,1.000000,1.000000,-0.011795,0.014311,1,MSFT,1.000000,1.000000,-0.011820,0.001089,0.479557,1.785008,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.573576,-0.819152,0.000000e+00,1.0,-0.002428,-0.001304,-0.006876,0.029842,-0.027673,0.011935,0.001627,-0.014651,-0.014109,-0.007251,0.001627,-0.014651,-0.004748,NaN,NaN,NaN,NaN,0.011935,0.011935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.015463,0.029842,-0.027673,0.008273,0.018990,0.029842,-0.027673,0.011935,0.032202,0.001741,0.012402,0.000435,-0.000870,-0.000653,0.008488,0.0,NaN,NaN,NaN,0.012402,0.012402,NaN,NaN,NaN,NaN,NaN,0.006490,1.0,0.004601,1.0,0.007566,1.0,0.010256,1.0,0.000000,1.0,-0.028063,1.0,-0.046649,1.0,-0.024164,1.0,-0.000544,1.0
3,2000-01-04 09:45:00,3.866009,0.398053,0.650672,1.404380,0.0,1.000000,1.000000,-0.005360,0.020915,1,MSFT,1.000000,1.000000,-0.013969,-0.001089,0.435599,-8.429669,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.555570,-0.831470,0.000000e+00,1.0,-0.004441,-0.006039,-0.010542,0.023180,-0.033963,0.005389,0.002695,-0.021025,-0.020487,-0.012430,0.002695,-0.013478,-0.004179,NaN,NaN,NaN,NaN,0.005389,0.005389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.008894,0.023180,-0.033963,0.001751,0.012398,0.023180,-0.033963,0.005389,0.032577,0.002104,0.012770,0.001451,-0.002466,-0.000290,0.006580,0.0,NaN,NaN,NaN,0.012770,0.012770,NaN,NaN,NaN,NaN,NaN,0.002154,1.0,-0.003782,1.0,0.002154,1.0,0.003766,1.0,-0.007578,1.0,-0.037907,1.0,-0.065151,1.0,-0.033996,1.0,-0.002700,1.0
4,2000-01-04 09:50:00,2.907437,1.274839,0.640596,4.255772,0.0,1.000000,1.000000,-0.003215,0.023117,1,MSFT,1.000000,1.000000,-0.012680,0.000218,0.445078,-14.098132,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,NaN,NaN,NaN,MSFT,1,0.537300,-0.843391,0.000000e+00,1.0,-0.003291,-0.006360,-0.009366,0.020978,-0.036042,0.003226,0.003226,-0.023132,-0.022594,-0.010438,0.003226,-0.010438,-0.000539,NaN,NaN,NaN,NaN,0.003226,0.003226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.006723,0.020978,-0.036042,-0.000405,0.010220,0.020978,-0.036042,0.003226,0.032655,0.002180,0.012846,0.001527,-0.002391,-0.000214,0.005178,0.0,NaN,NaN,NaN,0.012846,0.012846,NaN,NaN,NaN,NaN,NaN,0.004829,1.0,-0.004313,1.0,-0.001616,1.0,0.001612,1.0,-0.012994,1.0,-0.045114,1.0,-0.060424,1.0,-0.033922,1.0,-0.008644,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506401,2025-07-25 15:40:00,-3.187223,-2.437605,0.304440,17.774860,1.0,0.872843,1.081357,0.009809,0.007838,-1,MSFT,0.607204,0.722762,0.004698,0.003559,0.917999,21.574320,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.819152,-0.573576,1.224647e-16,-1.0,0.000503,0.000986,-0.003298,-0.005065,-0.017403,-0.009714,0.003883,-0.011478,-0.007777,0.000960,0.001017,-0.000107,0.000461,-0.027423,-0.068830,-0.155170,-0.167856,-0.017360,-0.031626,-0.003186,-0.332171,-0.018391,-0.030187,-0.018410,-0.042951,-0.104138,-0.177005,-0.018347,-0.005065,-0.018347,-0.011684,-0.014556,-0.005065,-0.017403,-0.009714,-0.000311,-0.003706,-0.003156,0.001936,-0.002370,-0.002024,0.001600,0.0,-0.020021,-0.047411,-0.078022,-0.011099,-0.022766,-0.000311,-0.242867,-0.001490,-0.010400,0.011949,-0.000765,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506402,2025-07-25 15:45:00,-3.353187,-2.091420,0.144395,11.882884,0.0,0.894688,1.078775,0.009036,0.007067,-1,MSFT,0.908817,0.726364,0.004911,0.003771,1.000000,21.460234,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.831470,-0.555570,1.224647e-16,-1.0,0.000634,0.001363,-0.002503,-0.004303,-0.016651,-0.008955,0.004652,-0.010721,-0.007017,0.001477,0.001477,-0.000136,0.000359,-0.026678,-0.068117,-0.154524,-0.167218,-0.016607,-0.030885,-0.002423,-0.331660,-0.017639,-0.029444,-0.017659,-0.042218,-0.103452,-0.176375,-0.017595,-0.004303,-0.017595,-0.010928,-0.013801,-0.004303,-0.016651,-0.008955,-0.000352,-0.003747,-0.003197,0.001895,-0.002411,-0.002065,0.001590,0.0,-0.020061,-0.047450,-0.078059,-0.011139,-0.022806,-0.000352,-0.242898,-0.001531,-0.010441,0.011958,-0.001261,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506403,2025-07-25 15:50:00,-4.645053,-4.004664,0.054670,4.081138,0.0,1.406802,1.085621,0.007765,0.005798,-1,MSFT,0.846949,0.728845,0.004682,0.003543,0.902754,19.143709,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.843391,-0.537300,1.224647e-16,-1.0,0.000948,0.002043,-0.001207,-0.003047,-0.015410,-0.007705,0.005920,-0.009473,-0.005764,0.002180,0.002180,-0.001126,0.000442,-0.025450,-0.066941,-0.153457,-0.166168,-0.015367,-0.029662,-0.001164,-0.330817,-0.016400,-0.028220,-0.016420,-0.041010,-0.102321,-0.175336,-0.016356,-0.003047,-0.016356,-0.009680,-0.012557,-0.003047,-0.015410,-0.007705,-0.000388,-0.003782,-0.003232,0.001859,-0.002447,-0.002101,0.001527,0.0,-0.020096,-0.047484,-0.078093,-0.011174,-0.022841,-0.000388,-0.242925,-0.001567,-0.010476,0.011973,-0.002954,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506404,2025-07-25 15:55:00,-5.233312,-4.252124,0.105488,-8.141213,0.0,1.629662,1.108175,0.004792,0.002831,-1,MSFT,0.684967,0.727525,0.004493,0.003354,0.586184,15.525219,1.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.854912,-0.518773,1.224647e-16,-1.0,0.001955,0.003895,0.001689,-0.000097,-0.012497,-0.004769,0.008896,-0.006542,-0.002823,0.004274,0.004274,-0.000603,0.001324,-0.022567,-0.064180,-0.150952,-0.163701,-0.012453,-0.026791,0.001791,-0.328837,-0.013490,-0.025345,-0.013509,-0.038173,-0.099665,-0.172896,-0.013446,-0.000097,-0.013446,-0.006750,-0.009636,-0.000097,-0.012497,-0.004769,-0.000425,-0.003819,-0.003269,0.001821,-0.002484,-0.002138,0.001427,0.0,-0.020133,-0.047520,-0.078127,-0.011211,-0.022878,-0.000425,-0.242954,-0.001604,-0.010513,0.012008,0.000409,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
506405,2025-07-25 16:00:00,-5.532922,-3.194700,0.138795,-15.798197,0.0,0.753124,0.977655,0.005203,0.003240,-1,MSFT,1.162845,0.746520,0.003862,0.002724,0.379329,7.227488,0.0,4.440928,6.168929,-1.498407,-0.853471,-0.192887,-0.397005,-0.580811,-0.486401,0.637741,-0.370965,-1.457372,1.459701,-0.798903,0.285457,1.0,1.0,46.77528,32.922661,13.525066,MSFT,4,-0.866025,-0.500000,1.224647e-16,-1.0,0.000773,0.002710,0.000867,-0.000506,-0.012901,-0.005176,0.008484,-0.006948,-0.003230,0.002389,0.002389,-0.001566,-0.000246,-0.022966,-0.064563,-0.151299,-0.164042,-0.012857,-0.027189,0.001382,-0.329111,-0.013893,-0.025743,-0.013912,-0.038566,-0.100033,-0.173234,-0.013849,-0.000506,-0.013849,-0.007156,-0.010040,-0.000506,-0.012901,-0.005176,-0.000474,-0.003867,-0.003317,0.001773,-0.002532,-0.002186,0.001191,0.0,-0.020180,-0.047566,-0.078171,-0.011259,-0.022925,-0.000474,-0.242990,-0.001652,-0.010561,0.012003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fileCheck.dtypes

timestamp                datetime64[us]
m5_rrs_rrs_spy                  float32
m5_rrs_rrs_sector               float32
m5_mom_lrsi                     float32
m5_mom_tsi                      float32
                              ...
target_cls_3d                   float32
target_reg_5d_logret            float32
target_cls_5d                   float32
target_reg_10d_logret           float32
target_cls_10d                  float32
Length: 115, dtype: object

In [2]:
# --- Configuration ---
# 1. Setup Paths
source_dir = '/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets'
dest_dir = './data'
ticker = 'AAPL'
filename = f"{ticker}.parquet"

# 2. Columns to explicitly DROP (Metadata only)
# We KEEP 'm5_ha_ha_color' and 'time_weekday' because they are valid features
cols_to_drop = ['ticker', 'ticker_d1'] 

# Create destination if it doesn't exist
os.makedirs(dest_dir, exist_ok=True)

In [8]:
print(f"--- Processing {ticker} ---")

try:
    # ---------------------------------------------------------
    # Step 1: Read the Parquet File
    # ---------------------------------------------------------
    file_path = os.path.join(source_dir, filename)
    df = pd.read_parquet(file_path)

    # ---------------------------------------------------------
    # Step 2: Handle Timestamp (Sidecar File) - CORRECTED
    # ---------------------------------------------------------
    if 'timestamp' in df.columns:
        print("Extracting timestamps...")
        
        # --- THE FIX IS HERE ---
        # 1. Force conversion to 'datetime64[ns]' (nanoseconds)
        # This ensures the integer value is scaled correctly for pandas defaults
        timestamps = df['timestamp'].astype('datetime64[ns]')
        
        # 2. Now convert to int64
        timestamps_array = timestamps.astype(np.int64).values
        
        # Save Timestamp .npy
        time_save_path = os.path.join(dest_dir, f"{ticker}_time.npy")
        np.save(time_save_path, timestamps_array)
        print(f"Saved timestamps to: {time_save_path}")
        
        # Drop from main df
        df = df.drop(columns=['timestamp'])

    # ---------------------------------------------------------
    # Step 3: Handle Features (Main Matrix)
    # ---------------------------------------------------------
    # ... [Rest of your code remains exactly the same] ...
    
    # Drop metadata
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors='ignore')
    features_array = df.astype(np.float32).values
    
    feature_save_path = os.path.join(dest_dir, f"{ticker}.npy")
    np.save(feature_save_path, features_array)
    
    # ---------------------------------------------------------
    # Step 4: Verification (Updated)
    # ---------------------------------------------------------
    print("\n" + "="*30)
    print("   VERIFICATION TEST   ")
    print("="*30)

    loaded_times = np.load(time_save_path, mmap_mode='r')
    
    print("\n--- Sample Data (Row 0) ---")
    
    # If the fix worked, this will now print ~2000 instead of 1970
    # pd.to_datetime defaults to unit='ns', which matches our new save format
    sample_time = pd.to_datetime(loaded_times[0])
    print(f"Timestamp: {sample_time}")
    
    # Double check it is not 1970
    if sample_time.year < 1980:
        print("WARNING: Date still looks like 1970. Check input units!")
    else:
        print("SUCCESS: Date looks correct.")

except Exception as e:
    print(f"\nERROR: {e}")

--- Processing AAPL ---
Extracting timestamps...
Saved timestamps to: ./data/AAPL_time.npy

==============================
   VERIFICATION TEST
==============================

--- Sample Data (Row 0) ---
Timestamp: 2000-01-04 09:30:00
SUCCESS: Date looks correct.

In [16]:
# A. Load Features with Memory Mapping
# This is instant because it doesn't read the whole file
loaded_features = np.load(feature_save_path, mmap_mode='r')

# B. Load Timestamps with Memory Mapping
loaded_times = np.load(time_save_path, mmap_mode='r')

# C. Check Alignment (Print first 3 rows)
print(f"\nLoaded Feature Shape (mmap): {loaded_features.shape}")
print(f"Loaded Time Shape (mmap): {loaded_times.shape}")

print("\n--- Sample Data (Row 0) ---")

# Convert int64 timestamp back to datetime for readability
sample_time = pd.to_datetime(loaded_times[0])
print(f"Timestamp: {sample_time}")

# Show first 5 features of row 0
print(f"Features (First 5): {loaded_features[0, :5]}")

# Verify 'm5_ha_ha_color' (Assuming it was a column, let's say it's at index -2)
# You might want to check where specific columns ended up if order matters to you
# For now, we just confirm it's all floats.
print(f"Data Type: {loaded_features.dtype}")

print("\nSUCCESS: Data is ready for RL training.")

loaded_features

Loaded Feature Shape (mmap): (506906, 112)
Loaded Time Shape (mmap): (506906,)

--- Sample Data (Row 0) ---
Timestamp: 2000-01-04 09:30:00
Features (First 5): [        nan         nan  0.44670305 10.54969     0.        ]
Data Type: float32

SUCCESS: Data is ready for RL training.

memmap([[        nan,         nan,  0.44670305, ...,  1.        ,
         -0.03345568,  1.        ],
        [ 1.3344522 , -0.322855  ,  0.49905837, ...,  1.        ,
         -0.03801306,  1.        ],
        [ 2.054531  ,  0.43629497,  0.67274237, ...,  1.        ,
         -0.04829136,  1.        ],
        ...,
        [-0.03826636,  0.6021224 ,  0.07254588, ...,         nan,
                 nan,         nan],
        [ 2.2483325 ,  3.2295198 ,  0.21870293, ...,         nan,
                 nan,         nan],
        [ 0.87602925,  3.2142515 ,  0.15354222, ...,         nan,
                 nan,         nan]], shape=(506906, 112), dtype=float32)

In [17]:
loaded_features.shape

(506906, 112)

In [18]:
import numpy as np
import pandas as pd
import os
import time
import psutil

# --- Configuration ---
ticker = 'AAPL'
data_dir = './data'
feature_path = os.path.join(data_dir, f"{ticker}.npy")
time_path = os.path.join(data_dir, f"{ticker}_time.npy")

# Parameters for the test
N_TRIALS = 10
EPISODE_WINDOW = 256  # Simulating an agent looking at last 64 bars
CLEAR_CACHE_WARNING = True

def get_process_memory():
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024  # MB

def benchmark_sampling(n_trials=10, window_size=64):
    print(f"--- Benchmarking: {ticker} ---")
    print(f"Window Size: {window_size} rows")
    print(f"Initial RAM Usage: {get_process_memory():.2f} MB")
    
    # 1. Open File in MMAP mode (Zero copy, nearly instant)
    # We do this OUTSIDE the loop because in your RL env, you open it once in __init__
    start_load = time.time()
    features_mmap = np.load(feature_path, mmap_mode='r')
    times_mmap = np.load(time_path, mmap_mode='r')
    print(f"File Open Time: {(time.time() - start_load)*1000:.4f} ms")
    
    max_idx = len(features_mmap) - window_size
    timings = []
    
    print(f"\nRunning {n_trials} random lookups...")
    print("-" * 60)
    print(f"{'Trial':<6} | {'Index':<10} | {'Read Time (ms)':<15} | {'Date Found'}")
    print("-" * 60)

    for i in range(n_trials):
        # A. Pick Random Start Index
        rand_idx = np.random.randint(0, max_idx)
        
        # B. Start Timer
        t0 = time.perf_counter()
        
        # C. The Critical Operation: Slicing + Copying
        # mmap returns a view. .copy() forces the OS to actually read the disk/cache
        obs_slice = features_mmap[rand_idx : rand_idx + window_size].copy()
        time_val = times_mmap[rand_idx] # Just reading the int64 timestamp
        
        # D. Stop Timer
        t1 = time.perf_counter()
        dt_ms = (t1 - t0) * 1000
        timings.append(dt_ms)
        
        # For display, convert timestamp
        time_str = str(pd.to_datetime(time_val))
        
        print(f"{i+1:<6} | {rand_idx:<10} | {dt_ms:<15.4f} | {time_str}")

    # --- Statistics ---
    avg_time = np.mean(timings)
    std_time = np.std(timings)
    min_time = np.min(timings)
    max_time = np.max(timings)
    
    print("-" * 60)
    print(f"\nFinal Statistics ({n_trials} trials):")
    print(f"Average Read Time: {avg_time:.4f} ms")
    print(f"Std Dev:           {std_time:.4f} ms")
    print(f"Fastest Read:      {min_time:.4f} ms")
    print(f"Slowest Read:      {max_time:.4f} ms")
    print(f"Final RAM Usage:   {get_process_memory():.2f} MB (Should be low!)")

    # Throughput Estimation
    # How many steps per second could the data loader theoretically support?
    steps_per_sec = 1000 / avg_time

    print(f"\nTheoretical Throughput: ~{int(steps_per_sec)} steps/second")

if __name__ == "__main__":
    if os.path.exists(feature_path):
        benchmark_sampling(N_TRIALS, EPISODE_WINDOW)
    else:
        print(f"File not found: {feature_path}. Run the conversion script first.")

--- Benchmarking: AAPL ---
Window Size: 256 rows
Initial RAM Usage: 795.66 MB
File Open Time: 0.3011 ms

Running 10 random lookups...
------------------------------------------------------------
Trial  | Index      | Read Time (ms)  | Date Found
------------------------------------------------------------
1      | 137250     | 0.5461          | 2006-12-12 09:55:00
2      | 300892     | 0.4140          | 2015-03-11 15:45:00
3      | 24641      | 0.4077          | 2001-03-30 15:25:00
4      | 208166     | 0.4024          | 2010-07-12 09:40:00
5      | 167377     | 0.3968          | 2008-06-20 10:05:00
6      | 347277     | 0.4012          | 2017-07-11 13:35:00
7      | 455828     | 0.4079          | 2022-12-23 11:35:00
8      | 52447      | 0.3955          | 2002-08-30 14:10:00
9      | 396172     | 0.3939          | 2019-12-26 09:55:00
10     | 98982      | 0.3944          | 2005-01-07 11:25:00
------------------------------------------------------------

Final Statistics (10 trials):
Average Read Time: 0.4160 ms
Std Dev:           0.0438 ms
Fastest Read:      0.3939 ms
Slowest Read:      0.5461 ms
Final RAM Usage:   867.36 MB (Should be low!)

Theoretical Throughput: ~2403 steps/second

In [25]:
import pandas as pd
import numpy as np
import os
import json
from tqdm import tqdm

# --- Configuration ---
source_dir = '/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets'
dest_dir = './data'
REFERENCE_TICKER = "AAPL" 
cols_to_drop = ['ticker', 'ticker_d1'] 

os.makedirs(dest_dir, exist_ok=True)
files = [f for f in os.listdir(source_dir) if f.endswith('.parquet')]

# ---------------------------------------------------------
# Step A: Establish the "Gold Standard" Schema
# ---------------------------------------------------------
print(f"Loading reference ticker ({REFERENCE_TICKER}) to establish schema...")
ref_path = os.path.join(source_dir, f"{REFERENCE_TICKER}.parquet")

if not os.path.exists(ref_path):
    raise FileNotFoundError(f"Reference ticker {REFERENCE_TICKER} not found in source!")

ref_df = pd.read_parquet(ref_path)

if 'timestamp' in ref_df.columns:
    ref_df = ref_df.drop(columns=['timestamp'])
ref_df = ref_df.drop(columns=[c for c in cols_to_drop if c in ref_df.columns], errors='ignore')

MASTER_FEATURES = ref_df.columns.tolist()
EXPECTED_COUNT = len(MASTER_FEATURES)

print(f"Standard Schema Established: {EXPECTED_COUNT} features.")

# Save Metadata
metadata = {
    "feature_names": MASTER_FEATURES,
    "num_features": EXPECTED_COUNT,
    "reference_ticker": REFERENCE_TICKER
}
with open(os.path.join(dest_dir, 'master_metadata.json'), 'w') as f:
    json.dump(metadata, f, indent=4)

# ---------------------------------------------------------
# Step B: Process All Files
# ---------------------------------------------------------
skipped_tickers = []
processed_count = 0

for file in tqdm(files, desc="Standardizing Data"):
    try:
        ticker_name = file.replace('.parquet', '')
        file_path = os.path.join(source_dir, file)
        
        # 1. Read
        df = pd.read_parquet(file_path)
        
        # 2. Extract Timestamp (BUT DO NOT SAVE YET)
        timestamps_array = None
        if 'timestamp' in df.columns:
            # Convert to correct units and store in memory variable
            timestamps_array = df['timestamp'].astype('datetime64[ns]').astype(np.int64).values
            # Drop from dataframe so it doesn't interfere with feature processing
            df = df.drop(columns=['timestamp'])
        
        # 3. Enforce Feature Consistency
        try:
            # Attempt to select exactly the columns we need
            df_clean = df[MASTER_FEATURES]
        except KeyError as e:
            # If columns are missing, we skip.
            # CRITICAL CHANGE: We haven't saved the time file yet, so nothing to clean up.
            missing_cols = list(set(MASTER_FEATURES) - set(df.columns))
            skipped_tickers.append({
                "ticker": ticker_name, 
                "reason": "Missing Columns",
                "missing_count": len(missing_cols),
                "example_missing": missing_cols[:3]
            })
            continue

        # 4. Convert Features
        features_array = df_clean.apply(pd.to_numeric, errors='coerce').astype(np.float32).values
        
        # Double check shape
        if features_array.shape[1] != EXPECTED_COUNT:
            skipped_tickers.append({"ticker": ticker_name, "reason": "Shape Mismatch"})
            continue
            
        # 5. FINAL SAVE (Atomic-ish)
        # Now that we know features are valid, we save both files.
        np.save(os.path.join(dest_dir, f"{ticker_name}.npy"), features_array)
        
        if timestamps_array is not None:
            np.save(os.path.join(dest_dir, f"{ticker_name}_time.npy"), timestamps_array)
            
        processed_count += 1
        
    except Exception as e:
        print(f"Error on {file}: {e}")

# ---------------------------------------------------------
# Step C: Report
# ---------------------------------------------------------
print("\n" + "="*40)
print(f"Processing Complete.")
print(f"Successfully Converted: {processed_count}")
print(f"Skipped Tickers:      {len(skipped_tickers)}")
print("="*40)

if skipped_tickers:
    print("\nSkipped Ticker Details (Outliers):")
    for item in skipped_tickers[:10]:
        print(f"{item['ticker']:<8} | {item['reason']}")

with open(os.path.join(dest_dir, 'skipped_report.json'), 'w') as f:
    json.dump(skipped_tickers, f, indent=4)

Loading reference ticker (AAPL) to establish schema...
Standard Schema Established: 112 features.

Standardizing Data: 100%|██████████| 318/318 [05:18<00:00,  1.00s/it]

========================================
Processing Complete.
Successfully Converted: 310
Skipped Tickers:      8
========================================

Skipped Ticker Details (Outliers):
CRWV     | Missing Columns
GEV      | Missing Columns
WBA      | Missing Columns
ETHA     | Missing Columns
PARA     | Missing Columns
HES      | Missing Columns
CRCL     | Missing Columns
BRK.B    | Missing Columns

In [23]:
import random

# --- Configuration ---
data_dir = './data'
NUM_TICKERS_TO_CHECK = 100   # How many different tickers to test
SAMPLES_PER_TICKER = 1     # How many random rows to read per ticker

def verify_dataset_integrity():
    print(f"--- Starting Global Integrity Check ---")
    print(f"Directory: {data_dir}")
    
    # 1. Discover all tickers based on the time files
    # We look for '_time.npy' to ensure we only check completed pairs
    all_files = os.listdir(data_dir)
    time_files = [f for f in all_files if f.endswith('_time.npy')]
    
    if not time_files:
        print("ERROR: No data files found!")
        return

    # Extract ticker names (remove '_time.npy')
    all_tickers = [f.replace('_time.npy', '') for f in time_files]
    print(f"Found {len(all_tickers)} total tickers.")
    
    # 2. Randomly select tickers to test
    selected_tickers = random.sample(all_tickers, min(NUM_TICKERS_TO_CHECK, len(all_tickers)))
    
    print(f"\nChecking {len(selected_tickers)} random tickers...")
    print("=" * 80)
    print(f"{'Ticker':<8} | {'Shape (Rows, Cols)':<20} | {'Sample Time':<22} | {'Feat[0]':<8} | {'Status'}")
    print("=" * 80)

    for ticker in selected_tickers:
        try:
            # Paths
            feature_path = os.path.join(data_dir, f"{ticker}.npy")
            time_path = os.path.join(data_dir, f"{ticker}_time.npy")
            
            # Check if pair exists
            if not os.path.exists(feature_path):
                print(f"{ticker:<8} | {'MISSING FEATURE FILE':<20} | {'---':<22} | {'---':<8} | FAIL")
                continue

            # 3. Load via Memory Map (Instant)
            features = np.load(feature_path, mmap_mode='r')
            times = np.load(time_path, mmap_mode='r')
            
            # 4. Consistency Checks
            if features.shape[0] != times.shape[0]:
                print(f"{ticker:<8} | {str(features.shape):<20} | {'MISMATCH':<22} | {'---':<8} | FAIL (Shape)")
                continue
                
            # 5. Random Sampling
            for _ in range(SAMPLES_PER_TICKER):
                # Pick random index
                idx = np.random.randint(0, len(features))
                
                # Read Data
                row_feats = features[idx]
                row_time_int = times[idx]
                
                # Decode Timestamp
                # Force unit='ns' to match our save format
                ts = pd.to_datetime(row_time_int, unit='ns')
                
                # Logic Check: Is the year valid? (Should be > 1980)
                if ts.year < 1980:
                    status = "FAIL (1970)"
                else:
                    status = "OK"

                # Print Row
                print(f"{ticker:<8} | {str(features.shape):<20} | {str(ts):<22} | {row_feats[0]:<8.3f} | {status}")
                
        except Exception as e:
            print(f"{ticker:<8} | {'ERROR':<20} | {str(e):<22} | {'---':<8} | CRASH")

    print("=" * 80)
    print("Check complete.")

if __name__ == "__main__":
    verify_dataset_integrity()

--- Starting Global Integrity Check ---
Directory: ./data
Found 318 total tickers.

Checking 100 random tickers...
================================================================================
Ticker   | Shape (Rows, Cols)   | Sample Time            | Feat[0]  | Status
================================================================================
ELV      | (371963, 112)        | 2008-05-19 13:35:00    | 0.168    | OK
TMUS     | (361360, 112)        | 2019-04-18 15:50:00    | 1.694    | OK
OKLO     | (23731, 112)         | 2024-08-07 13:30:00    | 2.619    | OK
NET      | (115873, 112)        | 2022-03-31 13:15:00    | 1.515    | OK
JCI      | (502811, 112)        | 2018-02-09 15:05:00    | -0.383   | OK
HAL      | (504902, 112)        | 2007-06-15 14:55:00    | 1.743    | OK
KHC      | (199147, 112)        | 2018-09-21 10:10:00    | 3.596    | OK
TLN      | (20442, 112)         | 2024-12-12 09:30:00    | 3.643    | OK
USB      | (504314, 112)        | 2011-01-26 14:55:00    | 0.372    | OK
CSCO     | (506213, 112)        | 2004-06-01 15:50:00    | 0.560    | OK
CAT      | (504895, 112)        | 2017-03-23 12:15:00    | -2.062   | OK
LOW      | (504276, 112)        | 2012-04-13 09:40:00    | 5.668    | OK
YUM      | (503978, 112)        | 2003-02-25 13:35:00    | -1.552   | OK
APA      | (504178, 112)        | 2021-02-24 12:00:00    | -1.412   | OK
GIS      | (504527, 112)        | 2010-12-09 14:55:00    | -0.146   | OK
KLAC     | (505738, 112)        | 2024-10-25 13:45:00    | 2.735    | OK
BEKE     | (97792, 112)         | 2025-07-21 11:55:00    | -0.233   | OK
CMCSA    | (493751, 112)        | 2011-05-24 12:50:00    | -2.086   | OK
KO       | (505136, 112)        | 2022-04-26 12:45:00    | -3.574   | OK
PYPL     | (199313, 112)        | 2024-08-16 15:40:00    | -2.684   | OK
W        | (213571, 112)        | 2022-06-28 12:20:00    | 2.330    | OK
AMD      | (505802, 112)        | 2002-12-17 10:10:00    | 3.577    | OK
NUE      | (502755, 112)        | 2011-05-02 15:40:00    | -1.133   | OK
PDD      | (138541, 112)        | 2023-03-06 14:10:00    | 0.561    | OK
SHEL     | (361111, 112)        | 2011-07-07 10:35:00    | 0.679    | OK
BMY      | (504558, 112)        | 2011-07-14 10:15:00    | -1.545   | OK
SO       | (504557, 112)        | 2019-12-24 12:40:00    | 1.015    | OK
MU       | (505661, 112)        | 2012-12-07 10:15:00    | -1.143   | OK
EBAY     | (505958, 112)        | 2018-01-18 14:00:00    | 0.613    | OK
PEP      | (505149, 112)        | 2007-08-03 15:35:00    | 1.364    | OK
PINS     | (124016, 112)        | 2025-05-16 13:45:00    | -0.763   | OK
MCK      | (503527, 112)        | 2019-11-20 15:25:00    | 0.303    | OK
PSX      | (261766, 112)        | 2018-08-29 11:30:00    | -3.545   | OK
ZS       | (145506, 112)        | 2022-06-15 10:45:00    | -0.084   | OK
CVNA     | (162573, 112)        | 2021-11-22 10:40:00    | -9.560   | OK
DG       | (310077, 112)        | 2010-02-10 10:00:00    | -4.212   | OK
LYB      | (292237, 112)        | 2020-03-05 10:15:00    | 0.880    | OK
PM       | (342986, 112)        | 2009-03-27 13:25:00    | 0.630    | OK
SNAP     | (166474, 112)        | 2019-05-17 14:40:00    | 3.291    | OK
HUM      | (501065, 112)        | 2024-12-02 15:20:00    | -3.787   | OK
BRK.B    | (488778, 106)        | 2014-02-13 14:20:00    | 0.345    | OK
ABT      | (504578, 112)        | 2008-07-25 12:50:00    | -1.038   | OK
CVX      | (470300, 112)        | 2011-05-05 12:25:00    | -1.851   | OK
ADI      | (504583, 112)        | 2010-05-26 11:55:00    | 0.531    | OK
UAL      | (293321, 112)        | 2017-03-29 12:15:00    | -2.499   | OK
SLB      | (504563, 112)        | 2016-04-12 11:15:00    | 0.525    | OK
AMZN     | (506465, 112)        | 2018-12-11 12:10:00    | 1.114    | OK
OTIS     | (105324, 112)        | 2022-09-27 10:05:00    | -0.993   | OK
DAL      | (361035, 112)        | 2019-01-11 14:00:00    | 1.326    | OK
CTSH     | (487187, 112)        | 2009-04-02 12:15:00    | -2.057   | OK
ISRG     | (468392, 112)        | 2018-12-19 12:10:00    | -1.003   | OK
ETHA     | (19901, 106)         | 2025-07-11 13:20:00    | 1.279    | OK
KEY      | (504171, 112)        | 2017-11-27 13:35:00    | 1.119    | OK
TOST     | (75807, 112)         | 2022-08-11 14:05:00    | 1.100    | OK
CL       | (504458, 112)        | 2022-03-01 10:25:00    | -1.441   | OK
PG       | (505131, 112)        | 2011-01-03 15:00:00    | 2.365    | OK
OKTA     | (163698, 112)        | 2022-07-18 12:30:00    | 1.734    | OK
DOCU     | (143258, 112)        | 2021-07-22 10:20:00    | 3.875    | OK
KMB      | (504472, 112)        | 2015-02-19 14:55:00    | -1.566   | OK
ULTA     | (349307, 112)        | 2022-11-21 14:15:00    | 0.208    | OK
CRWV     | (6319, 96)           | 2025-05-28 12:50:00    | -1.278   | OK
BIDU     | (395597, 112)        | 2016-11-16 11:10:00    | 0.563    | OK
CVS      | (504566, 112)        | 2015-11-20 10:40:00    | 0.432    | OK
META     | (261465, 112)        | 2012-11-30 15:30:00    | 3.762    | OK
ETN      | (250098, 112)        | 2019-06-21 14:15:00    | -0.409   | OK
CTVA     | (121447, 112)        | 2022-06-03 13:00:00    | -1.420   | OK
BAX      | (504529, 112)        | 2023-07-11 11:00:00    | -1.743   | OK
AFRM     | (89708, 112)         | 2021-04-15 12:35:00    | -3.334   | OK
NIO      | (136197, 112)        | 2021-11-01 12:15:00    | 0.706    | OK
NVDA     | (506195, 112)        | 2008-08-12 14:50:00    | -0.880   | OK
DUK      | (258299, 112)        | 2021-10-20 11:10:00    | 0.969    | OK
AIG      | (505487, 112)        | 2004-02-05 12:35:00    | 1.961    | OK
DVN      | (411395, 112)        | 2021-06-15 09:35:00    | -2.131   | OK
EOG      | (503205, 112)        | 2019-03-25 14:05:00    | 1.622    | OK
CRCL     | (2607, 82)           | 2025-06-16 15:20:00    | -2.262   | OK
PRU      | (466540, 112)        | 2014-06-13 15:35:00    | 2.371    | OK
HCA      | (284262, 112)        | 2020-02-26 11:35:00    | -1.456   | OK
AMT      | (268190, 112)        | 2018-07-02 14:45:00    | 2.354    | OK
MDLZ     | (476223, 112)        | 2023-08-30 10:55:00    | -1.036   | OK
BSX      | (504244, 112)        | 2005-11-10 13:20:00    | -2.425   | OK
MRVL     | (494023, 112)        | 2013-02-26 11:10:00    | 3.243    | OK
EMR      | (504098, 112)        | 2009-12-23 10:30:00    | 1.386    | OK
BP       | (492669, 112)        | 2012-06-04 13:30:00    | 2.139    | OK
JNJ      | (504989, 112)        | 2024-01-03 13:50:00    | 0.970    | OK
COIN     | (84879, 112)         | 2025-04-01 13:20:00    | -0.050   | OK
TWLO     | (179844, 112)        | 2017-07-26 15:00:00    | -1.025   | OK
FDX      | (504623, 112)        | 2017-02-08 14:00:00    | -2.768   | OK
COF      | (503939, 112)        | 2018-09-27 15:50:00    | 1.247    | OK
AA       | (173335, 112)        | 2019-03-05 15:55:00    | 4.791    | OK
EXC      | (488529, 112)        | 2010-10-12 11:20:00    | -1.620   | OK
DASH     | (91363, 112)         | 2022-06-08 12:55:00    | 1.103    | OK
JPM      | (505786, 112)        | 2005-08-01 11:20:00    | 1.599    | OK
HPE      | (192300, 112)        | 2017-04-10 15:15:00    | -0.594   | OK
U        | (95972, 112)         | 2023-08-04 12:20:00    | -2.787   | OK
PTON     | (115446, 112)        | 2020-04-27 11:20:00    | 0.288    | OK
KSS      | (504530, 112)        | 2009-08-19 13:40:00    | -1.107   | OK
HOOD     | (79033, 112)         | 2023-06-12 09:50:00    | -4.741   | OK
ACN      | (314519, 112)        | 2011-10-06 11:35:00    | -4.101   | OK
FLUT     | (28625, 112)         | 2025-07-03 10:10:00    | -13.411  | OK
HLT      | (229730, 112)        | 2021-08-24 09:35:00    | 11.219   | OK
================================================================================
Check complete.

In [24]:

# --- Configuration ---
source_dir = '/opt/rws/repos/RWS_LightGBM/data/reprocessed/final_merged_with_spy/ml_ready_with_targets'
REFERENCE_TICKER = "EOG" 

# Metadata columns to ignore during comparison
cols_to_ignore = ['ticker', 'ticker_d1', 'timestamp'] 

# ---------------------------------------------------------
# Step 1: Establish the "Gold Standard" from Reference
# ---------------------------------------------------------
ref_path = os.path.join(source_dir, f"{REFERENCE_TICKER}.parquet")

if not os.path.exists(ref_path):
    raise FileNotFoundError(f"Reference ticker {REFERENCE_TICKER} not found!")

# Read just the columns (efficient)
ref_df = pd.read_parquet(ref_path)
ref_cols = [c for c in ref_df.columns if c not in cols_to_ignore]
ref_set = set(ref_cols)

print(f"--- Schema Standard ({REFERENCE_TICKER}) ---")
print(f"Feature Count: {len(ref_cols)}")
print(f"Columns (First 5): {ref_cols[:5]}\n")

# ---------------------------------------------------------
# Step 2: Audit All Tickers
# ---------------------------------------------------------
files = [f for f in os.listdir(source_dir) if f.endswith('.parquet')]
skipped_log = []
valid_count = 0

print(f"Auditing {len(files)} files...")

for file in tqdm(files, desc="Checking Schemas"):
    try:
        # Read columns only
        # Note: pandas usually reads the whole file, but for just checking cols it's fast enough here.
        # If very slow, we could use pyarrow.parquet.read_schema()
        df = pd.read_parquet(os.path.join(source_dir, file))
        
        # Get feature columns for this ticker
        current_cols = [c for c in df.columns if c not in cols_to_ignore]
        current_set = set(current_cols)
        
        # CHECK 1: Feature Count
        if len(current_cols) != len(ref_cols):
            skipped_log.append({
                "ticker": file,
                "reason": "Count Mismatch",
                "details": f"Has {len(current_cols)} features (Expected {len(ref_cols)})"
            })
            continue

        # CHECK 2: Missing Specific Columns
        # We check if the Reference Set is a subset of Current Set
        # (This ensures all required EOG columns exist in the file)
        missing_cols = ref_set - current_set
        
        if missing_cols:
            skipped_log.append({
                "ticker": file,
                "reason": "Missing Required Features",
                "details": f"Missing {len(missing_cols)} cols: {list(missing_cols)[:3]}..."
            })
            continue
            
        valid_count += 1

    except Exception as e:
        skipped_log.append({"ticker": file, "reason": "Read Error", "details": str(e)})

# ---------------------------------------------------------
# Step 3: Final Report
# ---------------------------------------------------------
print("\n" + "="*50)
print(f"AUDIT COMPLETE")
print("="*50)
print(f"Valid Tickers:  {valid_count}")
print(f"Skipped Tickers: {len(skipped_log)}")
print("-" * 50)

if skipped_log:
    print(f"{'Ticker':<25} | {'Reason':<20} | {'Details'}")
    print("-" * 80)
    for item in skipped_log:
        print(f"{item['ticker']:<25} | {item['reason']:<20} | {item['details']}")
else:
    print("Perfect! All tickers match the schema.")

--- Schema Standard (EOG) ---
Feature Count: 112
Columns (First 5): ['m5_rrs_rrs_spy', 'm5_rrs_rrs_sector', 'm5_mom_lrsi', 'm5_mom_tsi', 'm5_mom_squeeze_on']

Auditing 318 files...

Checking Schemas: 100%|██████████| 318/318 [02:32<00:00,  2.08it/s]

==================================================
AUDIT COMPLETE
==================================================
Valid Tickers:  310
Skipped Tickers: 8
--------------------------------------------------
Ticker                    | Reason               | Details
--------------------------------------------------------------------------------
CRWV.parquet              | Count Mismatch       | Has 96 features (Expected 112)
GEV.parquet               | Count Mismatch       | Has 106 features (Expected 112)
WBA.parquet               | Count Mismatch       | Has 106 features (Expected 112)
ETHA.parquet              | Count Mismatch       | Has 106 features (Expected 112)
PARA.parquet              | Count Mismatch       | Has 106 features (Expected 112)
HES.parquet               | Count Mismatch       | Has 106 features (Expected 112)
CRCL.parquet              | Count Mismatch       | Has 82 features (Expected 112)
BRK.B.parquet             | Count Mismatch       | Has 106 features (Expected 112)